export {AlbumPage} from "./album/album";
export {CuentaPage} from "./cuenta/cuenta";
export {FichasFaltantesPage} from "./fichas-faltantes/fichas-faltantes";
export {FichasRepetidasPage} from "./fichas-repetidas/fichas-repetidas";
export {FichasTodasPage} from "./fichas-todas/fichas-todas";
export {IntercambioPage} from "./intercambio/intercambio";
export {LoginPage} from "./login/login";
export {RegistroPage} from "./registro/registro";
export {SolicitudesEntrantesPage} from "./solicitudes-entrantes/solicitudes-entrantes";
export {SolicitudesSalientesPage} from "./solicitudes-salientes/solicitudes-salientes";
export {TabsPage} from "./tabs/tabs";
export {HomePage} from "./home/home";
export {ConfiguracionPage } from "./configuracion/configuracion";
export { OlvidoContraseniaPage } from "./olvido-contrasenia/olvido-contrasenia";
export { ConfimarUsuarioPage } from "./confimar-usuario/confimar-usuario";
